import numpy as np 
concepts = [
    'one-hot encoding',
    'categorical variables',
    'features should be available at prediction time',
    'the self parameter', 
    'class methods',
    'decorators',
    'recursion',
    'ML v.s. stats',
    'OOP',
    'instance methods',
    'static methods',
    'normalization',
    'feature engineering',
    'BigQuery',
    'Apache Beam',
    'Preprocessing - remove examples you dont want to train on',
    'preprocessing - compute vocabularies for categorical columns',
    'preprocessing - compute aggregate statistics for numeric columns',
    'preprocessing - compute time-windowed stats for use as input features',
    'SQL',
    'tf.clip_by_value()',
    'tf.feature_column.numeric_column()',
    'tf.feature_column.bucketized_column',
    'Google DataFlow',
    'Google BigQuery',
    'Batched and streaming data sources',
    'Graph theory',
    'A pipeline is a directed graph of steps',
    'directed acyclic graph',
    'Sharding',
    'MapReduce',
    'Cluster computing',
    'Stateless functions',
    'Stateful functions',
    'Mainframe',
    'syntax variable',
    ''



]